version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - monitoring_net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 10
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - monitoring_net

  redis:
    image: redis:latest
    container_name: redis-spring
    ports:
      - "6379:6379"
    networks:
      - monitoring_net

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatdb
      MYSQL_USER: chat
      MYSQL_PASSWORD: chat1234
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - monitoring_net

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - monitoring_net
    volumes:
      - mongo_data:/data/db


#  app:
#    image: chat-server:test
#    container_name: chat-server
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#      - redis
#      - mongo
#      - kafka
#    environment:
#      SPRING_PROFILES_ACTIVE: prod
#      FRONTEND_URL: http://localhost:3001
#      MONGO_URI: mongodb://mongo:27017/chatbot
#      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#      MAIL_HOST: smtp.gmail.com
#      MAIL_PORT: 587
#      MAIL_USERNAME: your_email@gmail.com
#      MAIL_PASSWORD: your_email_password
#      DB_URL: jdbc:mysql://mysql:3306/chatdb
#      APP_DOMAIN_URL: http://localhost:3001
#      DB_USERNAME: chat
#      DB_PASSWORD: chat1234
#      REDIS_HOST: redis
#      REDIS_PORT: 6379
#      JWT_SECRET: T+FITVBc8qEi9tZ/TgN7mfZ9wb0BqArbh4B+RMZ9zKU=  # base64로 인코딩된 시크릿 키
#      GCS_BUCKET_NAME: your-gcs-bucket
#      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials.json
#    volumes:
#      - ./gcp-credentials.json:/app/credentials.json:ro
#    networks:
#      - monitoring_net
#



volumes:
  mysql_data:
  mongo_data:

networks:
  monitoring_net:
