opensearch:
  host: ${OPENSEARCH_HOST}
  port: ${OPENSEARCH_PORT}
  username: ${OPENSEARCH_USERNAME}
  password: ${OPENSEARCH_PASSWORD}
  scheme: ${OPENSEARCH_SCHEME:http}
  index:
    chat:
      name: ${OPENSEARCH_CHAT_INDEX:chat-index}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS} # ex) my-kafka.kafka.svc.cluster.local:9092
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: >
        org.apache.kafka.common.security.scram.ScramLoginModule required
        username="user1" password="${KAFKA_PASSWORD}";
      ssl.truststore.location: /app/config/kafka.truststore.jks
      ssl.truststore.password: ${KAFKA_TRUSTSTORE_PASSWORD}
      ssl.truststore.type: JKS    
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      enable-auto-commit: false
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:chatdb}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}          # ← 필요
    username: ${REDIS_USERNAME} 

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false    # SQL 쿼리 숨기기
        format_sql: false  # SQL 포맷팅 비활성화

logging.level:
  org.hibernate.SQL: OFF   # Hibernate SQL 로깅 끄기
  org.hibernate.type.descriptor.sql: OFF  # SQL 파라미터 로깅 끄기
  root: info              # 다른 로그는 info 레벨 유지
  org.springframework: info
  com.sns.project: debug  # 프로젝트 로그는 debug 레벨 유지
server:
  port: ${SERVER_PORT:8081}

# 쿠버네티스 환경 설정
# 환경변수를 통해 설정값을 주입받습니다.
# 
# OpenSearch 환경변수:
# - OPENSEARCH_HOST, OPENSEARCH_PORT, OPENSEARCH_USERNAME, OPENSEARCH_PASSWORD, OPENSEARCH_SCHEME, OPENSEARCH_CHAT_INDEX
# 
# Kafka 환경변수:
# - KAFKA_BOOTSTRAP_SERVERS
# 
# MySQL 환경변수:
# - MYSQL_HOST, MYSQL_PORT, MYSQL_DATABASE, MYSQL_USERNAME, MYSQL_PASSWORD
# 
# Redis 환경변수:
# - REDIS_HOST, REDIS_PORT
# 
# Server 환경변수:
# - SERVER_PORT
