spring:
  frontend:
    url: http://localhost:3001
    
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false

    producer:
      acks: all
      retries: 2147483647
      properties:
        enable.idempotence: true

  datasource:
    url: jdbc:postgresql://localhost:5433/chatdb
    username: chat
    password: chat1234
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379  # 개발 환경

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false    # SQL 쿼리 숨기기
        format_sql: false  # SQL 포맷팅 비활성화

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

logging.level:
  org.hibernate.SQL: OFF   # Hibernate SQL 로깅 끄기
  org.hibernate.type.descriptor.sql: OFF  # SQL 파라미터 로깅 끄기
  root: info              # 다른 로그는 info 레벨 유지
  org.springframework: info
  com.sns.project: debug  # 프로젝트 로그는 debug 레벨 유지


jwt:
  expiration: 900000  # 15분
  refresh-expiration: 604800000  # 7일
  secret: T+FITVBc8qEi9tZ/TgN7mfZ9wb0BqArbh4B+RMZ9zKU=

app:
  auth:
    cookie:
      access-token-name: ACCESS_TOKEN
      refresh-token-name: REFRESH_TOKEN
      csrf-token-name: XSRF-TOKEN
      secure: false
      http-only: true
      same-site: Lax
      path: /
      max-age-seconds: 900
      refresh-max-age-seconds: 604800
  kafka:
    topics:
      chat-message-created: chat.message.created
      chat-room-read: chat.room.read
      chat-dlq: chat.dlq
    consumer:
      max-retry-count: 3
      retry-backoff-ms: 1000
  outbox:
    relay:
      fixed-delay-ms: 1000
      batch-size: 100
      max-retry-count: 10


springdoc:
  api-docs:
    enabled: true  # API 문서 활성화
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 접근 경로
    operationsSorter: method  # API 문서에서 HTTP 메서드 정렬
    tagsSorter: alpha  # API 태그 알파벳 정렬
    display-request-duration: true  # 요청 처리 시간 표시
